### ISSUE TITLE
relative url check fails using seo:scan-url

### ISSUE THREAD

**Issue by marispro** [vormkracht10/laravel-seo-scanner#15]
When im running scanner from localhost, but some webpage have relative url, for example `<a href="/home">Home</a>,` then scanner tries to open his own page:  `http://localhost/home`

**Comment by Baspa** [comment]
I'm gonna take a look at this, thanks for mentioning it @marispro

**Comment by Baspa** [comment]
Do you have your `APP_URL` configured in your `.env` file? @marispro

**Comment by marispro** [comment]
> Do you have your `APP_URL` configured in your `.env` file? @marispro

Yes I have, but it is not related because I check another website.

**Comment by Baspa** [comment]
@marispro this should be fixed in #17. Version v1.1.0 contains the right fix.
