### ISSUE TITLE
websites blocked by cloudflare dns

### ISSUE THREAD

**Issue by allotmentandy** [vormkracht10/laravel-seo-scanner#21]
Hi, i am loving this tool, so useful, but a number of the sites i am checking are blocked by cloudflare 

is there any solution to allow this tool to bypass cloudflare gatekeeping?

thanks in advance.

**Comment by markvaneijk** [comment]
Hi @allotmentandy, we could make an option where you can provide the actual IP of the domain your testing. We can then use this to make the request using this IP address to bypass Cloudflare and contact the server directly.

Is this something you're looking for?

**Comment by allotmentandy** [comment]
that would be fantastic

**Comment by markvaneijk** [comment]
Started tinkering on this feature. Should be done soon.

**Comment by Baspa** [comment]
This issue is fixed in #22
